global_costmap:
#  global_frame: map
#  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
 
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "rtabmap_ros::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}




